import {
  ANIMACY_LABEL_PATTERNS,
  ASPECT_LABEL_PATTERNS,
  CASE_LABEL_PATTERNS,
  CONJUGATION_LABEL_PATTERNS,
  DECLENSION_LABEL_PATTERNS,
  MOVEMENT_VERB_PATTERNS,
  NOMINAL_GENDER_LABEL_PATTERNS,
  PLURAL_LABEL_PATTERNS,
  TENSE_PERSON_LABEL_PATTERNS,
} from "@/lib/knowledge/pedagogy/strategy/label-patterns";
import type { TPedagogicalStrategy } from "@/lib/knowledge/pedagogy/strategy/strategy-types";
import type { TKnowledgePartOfSpeech } from "@/types/knowledge";

const VERB_STRATEGY: TPedagogicalStrategy = {
  id: "verb",
  allowedReferenceSections: [
    "Aspect",
    "Paire aspectuelle",
    "Type de conjugaison",
    "Paradigme principal",
    "Conjugaison",
    "Formes principales",
    "Temps",
    "Personne",
    "Voix",
    "Verbe de mouvement",
    "Préverbes",
    "Schéma de mouvement",
    "Transitivité",
    "Constructions",
    "Régimes",
    "Formulations fréquentes",
    "Erreurs fréquentes",
    "Confusions",
    "Conseils",
    "Faux amis",
    "Synonymes",
    "Antonymes",
    "Collocations",
    "Sens central",
    "Sens élargi",
    "Progression",
    "Concepts liés",
    "Résumé",
    "À retenir",
  ],
  forbiddenReferenceSections: [
    "Genre",
    "Animacité",
    "Déclinaison",
    "Pluriel",
    "Paradigme des cas",
    "Cas gouvernés",
    "Cas",
    "Cas compatibles",
  ],
  forbiddenLabelPatterns: [
    ...CASE_LABEL_PATTERNS,
    ...ANIMACY_LABEL_PATTERNS,
    ...DECLENSION_LABEL_PATTERNS,
    ...NOMINAL_GENDER_LABEL_PATTERNS.filter((p) => !/\bneutre\b/i.test(p.source)),
  ],
  forbiddenMorphologyFields: [
    "declensionClass",
    "animacy",
    "caseParadigm",
    "plural",
    "declension",
    "pronounParadigm",
    "pronounType",
  ],
  forbiddenNextFormPatterns: CASE_LABEL_PATTERNS,
};

const NOUN_STRATEGY: TPedagogicalStrategy = {
  id: "noun",
  allowedReferenceSections: [
    "Genre",
    "Animacité",
    "Déclinaison",
    "Pluriel",
    "Paradigme des cas",
    "Cas gouvernés",
    "Irrégularités",
    "Constructions",
    "Régimes",
    "Formulations fréquentes",
    "Erreurs fréquentes",
    "Confusions",
    "Conseils",
    "Faux amis",
    "Synonymes",
    "Antonymes",
    "Collocations",
    "Sens central",
    "Sens élargi",
    "Progression",
    "Concepts liés",
    "Résumé",
    "À retenir",
  ],
  forbiddenReferenceSections: [
    "Conjugaison",
    "Type de conjugaison",
    "Paradigme principal",
    "Aspect",
    "Paire aspectuelle",
    "Temps",
    "Personne",
    "Voix",
    "Verbe de mouvement",
    "Préverbes",
    "Schéma de mouvement",
    "Transitivité",
  ],
  forbiddenLabelPatterns: [
    ...CONJUGATION_LABEL_PATTERNS,
    ...ASPECT_LABEL_PATTERNS,
    ...TENSE_PERSON_LABEL_PATTERNS,
    ...MOVEMENT_VERB_PATTERNS,
  ],
  forbiddenMorphologyFields: [
    "conjugationClass",
    "conjugationParadigm",
    "aspect",
    "aspectPair",
    "tense",
    "person",
    "voice",
    "movementType",
    "preverbs",
  ],
  forbiddenNextFormPatterns: [
    ...CONJUGATION_LABEL_PATTERNS,
    ...ASPECT_LABEL_PATTERNS,
    ...TENSE_PERSON_LABEL_PATTERNS,
  ],
};

const ADJECTIVE_STRATEGY: TPedagogicalStrategy = {
  id: "adjective",
  allowedReferenceSections: [
    "Accord",
    "Déclinaison",
    "Comparatif",
    "Superlatif",
    "Forme courte",
    "Paradigme",
    "Formes principales",
    "Irrégularités",
    "Constructions",
    "Régimes",
    "Formulations fréquentes",
    "Erreurs fréquentes",
    "Confusions",
    "Conseils",
    "Faux amis",
    "Synonymes",
    "Antonymes",
    "Collocations",
    "Sens central",
    "Sens élargi",
    "Progression",
    "Concepts liés",
    "Résumé",
    "À retenir",
  ],
  forbiddenReferenceSections: [
    "Conjugaison",
    "Type de conjugaison",
    "Aspect",
    "Paire aspectuelle",
    "Temps",
    "Personne",
    "Voix",
    "Verbe de mouvement",
    "Préverbes",
    "Animacité",
  ],
  forbiddenLabelPatterns: [
    ...CONJUGATION_LABEL_PATTERNS,
    ...ASPECT_LABEL_PATTERNS,
    ...TENSE_PERSON_LABEL_PATTERNS,
    ...ANIMACY_LABEL_PATTERNS,
    ...MOVEMENT_VERB_PATTERNS,
  ],
  forbiddenMorphologyFields: [
    "conjugationClass",
    "conjugationParadigm",
    "aspect",
    "aspectPair",
    "tense",
    "person",
    "voice",
    "movementType",
    "preverbs",
    "animacy",
    "pronounType",
  ],
  forbiddenNextFormPatterns: [
    ...CONJUGATION_LABEL_PATTERNS,
    ...ASPECT_LABEL_PATTERNS,
  ],
};

const PRONOUN_STRATEGY: TPedagogicalStrategy = {
  id: "pronoun",
  allowedReferenceSections: [
    "Type",
    "Accord",
    "Paradigme",
    "Formes principales",
    "Cas",
    "Formes particulières",
    "Emplois",
    "Régimes",
    "Formulations fréquentes",
    "Erreurs fréquentes",
    "Confusions",
    "Conseils",
    "Faux amis",
    "Synonymes",
    "Antonymes",
    "Collocations",
    "Sens central",
    "Sens élargi",
    "Progression",
    "Concepts liés",
    "Résumé",
    "À retenir",
  ],
  forbiddenReferenceSections: [
    "Conjugaison",
    "Type de conjugaison",
    "Aspect",
    "Paire aspectuelle",
    "Temps",
    "Personne",
    "Voix",
    "Verbe de mouvement",
    "Préverbes",
    "Animacité",
    "Genre",
  ],
  forbiddenLabelPatterns: [
    ...CONJUGATION_LABEL_PATTERNS,
    ...ASPECT_LABEL_PATTERNS,
    ...TENSE_PERSON_LABEL_PATTERNS,
    ...ANIMACY_LABEL_PATTERNS,
    ...MOVEMENT_VERB_PATTERNS,
  ],
  forbiddenMorphologyFields: [
    "conjugationClass",
    "conjugationParadigm",
    "aspect",
    "aspectPair",
    "tense",
    "person",
    "voice",
    "movementType",
    "preverbs",
    "animacy",
    "declensionClass",
    "plural",
  ],
  forbiddenNextFormPatterns: [
    ...CONJUGATION_LABEL_PATTERNS,
    ...ASPECT_LABEL_PATTERNS,
  ],
};

const ADVERB_STRATEGY: TPedagogicalStrategy = {
  id: "adverb",
  allowedReferenceSections: [
    "Sens",
    "Comparatif",
    "Constructions",
    "Régimes",
    "Formulations fréquentes",
    "Erreurs fréquentes",
    "Confusions",
    "Conseils",
    "Faux amis",
    "Synonymes",
    "Antonymes",
    "Collocations",
    "Sens central",
    "Sens élargi",
    "Progression",
    "Concepts liés",
    "Résumé",
    "À retenir",
  ],
  forbiddenReferenceSections: [
    "Conjugaison",
    "Aspect",
    "Genre",
    "Animacité",
    "Déclinaison",
    "Paradigme des cas",
    "Paradigme",
    "Cas gouvernés",
    "Temps",
    "Personne",
  ],
  forbiddenLabelPatterns: [
    ...CONJUGATION_LABEL_PATTERNS,
    ...ASPECT_LABEL_PATTERNS,
    ...CASE_LABEL_PATTERNS,
    ...ANIMACY_LABEL_PATTERNS,
    ...DECLENSION_LABEL_PATTERNS,
    ...TENSE_PERSON_LABEL_PATTERNS,
  ],
  forbiddenMorphologyFields: [
    "conjugationClass",
    "conjugationParadigm",
    "caseParadigm",
    "declensionClass",
    "animacy",
    "aspect",
    "aspectPair",
    "gender",
    "plural",
    "pronounParadigm",
  ],
  forbiddenNextFormPatterns: [
    ...CASE_LABEL_PATTERNS,
    ...CONJUGATION_LABEL_PATTERNS,
  ],
};

const PREPOSITION_STRATEGY: TPedagogicalStrategy = {
  id: "preposition",
  allowedReferenceSections: [
    "Sens",
    "Cas gouvernés",
    "Variantes",
    "Nuances",
    "Constructions",
    "Régimes",
    "Formulations fréquentes",
    "Erreurs fréquentes",
    "Confusions",
    "Conseils",
    "Faux amis",
    "Synonymes",
    "Antonymes",
    "Collocations",
    "Sens central",
    "Sens élargi",
    "Progression",
    "Concepts liés",
    "Résumé",
    "À retenir",
  ],
  forbiddenReferenceSections: [
    "Conjugaison",
    "Aspect",
    "Genre",
    "Animacité",
    "Déclinaison",
    "Paradigme des cas",
    "Paradigme",
    "Temps",
    "Personne",
    "Verbe de mouvement",
  ],
  forbiddenLabelPatterns: [
    ...CONJUGATION_LABEL_PATTERNS,
    ...ASPECT_LABEL_PATTERNS,
    ...ANIMACY_LABEL_PATTERNS,
    ...DECLENSION_LABEL_PATTERNS,
    ...TENSE_PERSON_LABEL_PATTERNS,
    ...MOVEMENT_VERB_PATTERNS,
  ],
  forbiddenMorphologyFields: [
    "conjugationClass",
    "conjugationParadigm",
    "caseParadigm",
    "declensionClass",
    "animacy",
    "aspect",
    "aspectPair",
    "gender",
    "plural",
    "pronounParadigm",
    "movementType",
  ],
  forbiddenNextFormPatterns: [
    ...CONJUGATION_LABEL_PATTERNS,
    ...ASPECT_LABEL_PATTERNS,
    ...ANIMACY_LABEL_PATTERNS,
  ],
};

const CONJUNCTION_STRATEGY: TPedagogicalStrategy = {
  id: "conjunction",
  allowedReferenceSections: [
    "Sens",
    "Constructions",
    "Régimes",
    "Formulations fréquentes",
    "Erreurs fréquentes",
    "Confusions",
    "Conseils",
    "Faux amis",
    "Synonymes",
    "Antonymes",
    "Collocations",
    "Sens central",
    "Sens élargi",
    "Progression",
    "Concepts liés",
    "Résumé",
    "À retenir",
  ],
  forbiddenReferenceSections: [
    "Conjugaison",
    "Aspect",
    "Genre",
    "Animacité",
    "Déclinaison",
    "Paradigme des cas",
    "Paradigme",
    "Cas gouvernés",
    "Temps",
    "Personne",
  ],
  forbiddenLabelPatterns: [
    ...CONJUGATION_LABEL_PATTERNS,
    ...ASPECT_LABEL_PATTERNS,
    ...CASE_LABEL_PATTERNS,
    ...ANIMACY_LABEL_PATTERNS,
    ...DECLENSION_LABEL_PATTERNS,
    ...TENSE_PERSON_LABEL_PATTERNS,
  ],
  forbiddenMorphologyFields: [
    "conjugationClass",
    "conjugationParadigm",
    "caseParadigm",
    "declensionClass",
    "animacy",
    "aspect",
    "aspectPair",
    "gender",
    "plural",
    "pronounParadigm",
  ],
  forbiddenNextFormPatterns: [
    ...CASE_LABEL_PATTERNS,
    ...CONJUGATION_LABEL_PATTERNS,
  ],
};

const PARTICLE_STRATEGY: TPedagogicalStrategy = {
  id: "particle",
  allowedReferenceSections: [
    "Sens",
    "Constructions",
    "Régimes",
    "Formulations fréquentes",
    "Erreurs fréquentes",
    "Confusions",
    "Conseils",
    "Faux amis",
    "Synonymes",
    "Antonymes",
    "Collocations",
    "Sens central",
    "Sens élargi",
    "Progression",
    "Concepts liés",
    "Résumé",
    "À retenir",
  ],
  forbiddenReferenceSections: [
    "Conjugaison",
    "Aspect",
    "Genre",
    "Animacité",
    "Déclinaison",
    "Paradigme des cas",
    "Paradigme",
    "Cas gouvernés",
    "Temps",
    "Personne",
  ],
  forbiddenLabelPatterns: [
    ...CONJUGATION_LABEL_PATTERNS,
    ...ASPECT_LABEL_PATTERNS,
    ...CASE_LABEL_PATTERNS,
    ...ANIMACY_LABEL_PATTERNS,
    ...DECLENSION_LABEL_PATTERNS,
    ...TENSE_PERSON_LABEL_PATTERNS,
  ],
  forbiddenMorphologyFields: [
    "conjugationClass",
    "conjugationParadigm",
    "caseParadigm",
    "declensionClass",
    "animacy",
    "aspect",
    "aspectPair",
    "gender",
    "plural",
    "pronounParadigm",
  ],
  forbiddenNextFormPatterns: [
    ...CASE_LABEL_PATTERNS,
    ...CONJUGATION_LABEL_PATTERNS,
  ],
};

const GENERIC_STRATEGY: TPedagogicalStrategy = {
  id: "unknown",
  allowedReferenceSections: [],
  forbiddenReferenceSections: [],
  forbiddenLabelPatterns: [],
  forbiddenMorphologyFields: [],
  forbiddenNextFormPatterns: [],
};

const STRATEGY_MAP: Record<TKnowledgePartOfSpeech, TPedagogicalStrategy> = {
  verb: VERB_STRATEGY,
  noun: NOUN_STRATEGY,
  adjective: ADJECTIVE_STRATEGY,
  pronoun: PRONOUN_STRATEGY,
  adverb: ADVERB_STRATEGY,
  preposition: PREPOSITION_STRATEGY,
  conjunction: CONJUNCTION_STRATEGY,
  particle: PARTICLE_STRATEGY,
};

export function normalizePartOfSpeech(
  partOfSpeech: string | null | undefined,
): TKnowledgePartOfSpeech | null {
  if (!partOfSpeech) {
    return null;
  }

  const normalized = partOfSpeech.trim().toLowerCase();

  if (normalized in STRATEGY_MAP) {
    return normalized as TKnowledgePartOfSpeech;
  }

  return null;
}

export function getPedagogicalStrategy(
  partOfSpeech: string | null | undefined,
): TPedagogicalStrategy {
  const normalized = normalizePartOfSpeech(partOfSpeech);

  if (!normalized) {
    return GENERIC_STRATEGY;
  }

  return STRATEGY_MAP[normalized];
}

export {
  VERB_STRATEGY,
  NOUN_STRATEGY,
  ADJECTIVE_STRATEGY,
  PRONOUN_STRATEGY,
  ADVERB_STRATEGY,
  PREPOSITION_STRATEGY,
  CONJUNCTION_STRATEGY,
  PARTICLE_STRATEGY,
  GENERIC_STRATEGY,
};
